config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#index'
  get  '/about',   to: 'static_pages#about'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  post '/save_habit', to:'habits#save_achievement'
  resources :habits, only: [:index]
  resources :hobbies, only: [:index, :new, :create, :destroy]
  
  get '/hobbies/csv_output', to:'hobbies#csv_output'
  
  get '/daily_habit/new' => 'habits#new_daily'
  get '/weekly_habit/new' => 'habits#new_weekly'
  post '/daily_habit' => 'habits#create_daily'
  post '/weekly_habit' => 'habits#create_weekly'
  delete "/daily_habit/:id"=> "habits#daily_destroy"
  delete "/weekly_habit/:id"=> "habits#weekly_destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/controllers/hobbies_controller.rb
require 'csv'
class HobbiesController < ApplicationController
  
  def index
    @categories = Category.joins(:hobbies).where(hobbies: {user_id: current_user}).uniq
  end 
    
  def new
    @hobby = Hobby.new
  end 
  
  def create
    @hobby = current_user.hobbies.build(hobby_params)
    if @hobby.save
      flash[:success] = "Logged it successfully!"
      redirect_to hobbies_path
    else
      flash.now[:danger] = "Failed to record... :("
      render :new
    end
  end
  
  def destroy
    hobby=Hobby.find(params[:id])
    hobby.delete
    redirect_to hobbies_path, success: "Deleted it successfully!"
  end
  
  def csv_output
    @hobbies = Hobby.where(user_id: current_user, category_id: params[:category_id])
    respond_to do |format|
      format.html do
          #html用の処理を書く
      end 
      format.csv do
          #csv用の処理を書く
          send_data render_to_string, filename: "hobbies.csv", type: :csv
      end
    end
  end
  
  private
    def hobby_params
      params.require(:hobby).permit(:title, :impression, :category_id)
    end
end

app/helpers/hobbys_helper.rb
module HobbysHelper
end

app/views/hobbies/index.html.erb
<% provide(:title, 'Hobby') %>

<div class="hobbies-new-wrapper">
  <div class="hobbies-container container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        
        <h1><%=current_user.name%><%= t('hobbies.index.title')%></h1>
        
        
        <%= link_to t('hobbies.index.button'), new_hobby_path, class: 'btn btn-info' %>
        
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              　<%= t('hobbies.index.dropdown') %>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item">Movie</a>
              <a class="dropdown-item">Book</a>
              <a class="dropdown-item">TV show</a>
              <a class="dropdown-item">Study</a>
              <a class="dropdown-item">Game</a>
              <a class="dropdown-item">Travel</a>
              <a class="dropdown-item">Others</a>
            </div>
          </div>
          <script>
            $(".dropdown-item").on("click",function(){
              console.log($(this).text());
              var select_id = $(this).text();
              $(".category_area").addClass("d-none");
              $("#"+select_id).removeClass("d-none");
            });
          </script>
          
          <div class="row row-cols-1 row-cols-md-2">
            <% @categories.each do |category| %>
              <div class="col mb-4 d-none category_area" id="<%= category.name %>">
                <div class="card text-info">
                  <div class="card-header text-white">
                    <%= category.name %>
                  </div>
                  <% category.hobbies.each do |hobby| %>
                    <div class ="card-body">
                      <h5 class="card-title"><%= hobby.title %></h5>
                      <p class="card-text">🌟<%= hobby.impression %></p>
                      <%= link_to "Delete", "/hobbies/#{hobby.id}", method: :delete, class: "btn-sm btn btn-danger" %>
                    </div>
                    <hr>
                  <% end %>
                  <div class='card-body'>
                    <%= link_to "CSV出力", hobbies_csv_output_path(format: :csv, category_id: category.id), class: "small" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        
      <%= image_tag 'icons/cat_computer.png', size: '200x200'%>
      </div>
    </div>
  </div>
</div>

app/views/hobbies/new.html.erb
<div class="habits-new-wrapper">
  <div class="habits-container">
    <div class="row">
      <div class='col-md-8 mx-auto'>
        <div class='row'>
          <div class='col-md-6 mx-auto'>
            <h1 class="text-center text-black"><%= t('hobbies.new.title') %></h1>
            
            <%= form_for (@hobby) do |f| %>
              <div class="form-group">
                <%= f.label t('dictionary.label.category') %>
                <%= f.select :category_id, [["Movie", "1"], ["Book", "2"], ["TV show", "3"], ["Study", "4"], ["Game", "5"],  ["Travel", "6"], ["Others", "7"]], class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label t('hobbies.new.label'), class: 'text-black' %>
                <%= f.text_field :title, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label t('hobbies.new.label2'), class: 'text-black' %>
                <%= f.text_field :impression, class: 'form-control' %>
              </div>
              <%= f.submit t('dictionary.button.send'), class:"btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>