config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#index'
  get  '/about',   to: 'static_pages#about'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  post '/save_habit', to:'habits#save_achievement'
  resources :habits, only: [:index]
  resources :hobbies, only: [:index, :new, :create, :destroy]
  
  get '/hobbies/csv_output', to:'hobbies#csv_output'
  
  get '/daily_habit/new' => 'habits#new_daily'
  get '/weekly_habit/new' => 'habits#new_weekly'
  post '/daily_habit' => 'habits#create_daily'
  post '/weekly_habit' => 'habits#create_weekly'
  delete "/daily_habit/:id"=> "habits#daily_destroy"
  delete "/weekly_habit/:id"=> "habits#weekly_destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController

  def index
    @daily_habit = DailyHabit.all
    @weekly_habit = WeeklyHabit.all
  end
  
  def new_daily
    @habit = DailyHabit.new
  end
  
  def new_weekly
    @habit = WeeklyHabit.new
  end
  
  def create_daily
    @habit = current_user.daily_habits.new(daily_habit_params)
    if @habit.save
      flash[:success] = "Registerd your new habits successfully!"
      redirect_to habits_path
    else
      flash.now[:danger] = "Registration failed... :("
      render :new_daily
    end
  end
  
  def create_weekly
    @habit = current_user.weekly_habits.new(weekly_habit_params)
    if @habit.save
      flash[:success] = "Registerd your new habits successfully!"
      redirect_to habits_path
    else
      flash.now[:danger] = "Registration failed... :("
      render :new_weekly
    end
  end
  
  def create
    @habit = current_user.habits.new(habit_params)
    if @habit.save!
      flash[:success] = "Registerd your new habits successfully!"
      redirect_to habits_path
    else
      flash.now[:danger] = "Registration has been failed... :("
      render :new
    end
  end
  
  def update
    a
  end
  
  def save_achievement
    if  !params[:achievement_daily].nil?
       params[:achievement_daily].each do |key, d_a|
        if DailyAchievement.find_by(daily_habit_id: d_a.to_i, created_at: Time.zone.now.all_day).nil?
          current_user.daily_achievements.create(daily_habit_id: d_a.to_i)
        end
       end
    end
    
    if  !params[:achievement_weekly].nil?
      params[:achievement_weekly].each do |key, w_a|
        if WeeklyAchievement.find_by(weekly_habit_id: w_a.to_i, created_at: 1.week.ago..Date.today.end_of_day).nil?
          current_user.weekly_achievements.create(weekly_habit_id: w_a.to_i)
        end
      end
    end
    redirect_to habits_path, success: "Way to go!"
  end
  
  def daily_destroy
    habit=DailyHabit.find(params[:id])
    habit.daily_achievements.delete_all
    habit.delete
    redirect_to habits_path, success: "Your daily habit has been deleted!"
  end
  
  def weekly_destroy
    habit=WeeklyHabit.find(params[:id])
    habit.weekly_achievements.delete_all
    habit.delete
    redirect_to habits_path, success: "Your weekly habit has been deleted!"
  end
  
  
  private
  def daily_habit_params
    params.fetch(:daily_habit).permit(:name)
  end
  def weekly_habit_params
    params.fetch(:weekly_habit).permit(:name)
  end

end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/_cat_image.html.erb
<%= image_tag "icons/cat_straight.png" %>

      

app/views/habits/_smile_cat_image.html.erb
<%= image_tag "icons/cat_smile.png" %>

app/views/habits/index.html.erb
<% provide(:title, 'Habit') %>

<div class="habits-new-wrapper">
  <div class="habits-container container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <h1><%= t('habits.index.title') %></h1>
        <h2><%= t('habits.index.explain') %></h2>
        <%= link_to t("dictionary.button.daily"), daily_habit_new_path, class: 'btn btn-info' %>
        <%= link_to t("dictionary.button.weekly"), weekly_habit_new_path, class: 'btn btn-info' %>
        <hr>

        <h2><%= t('habits.index.explain2') %></h2>

      <div class='card'>
        <div class='card-header'>
          <h2 class="text-center text-black"><%= t('habits.index.title_d') %></h2>
        </div>
      
      <%= form_with(url: save_habit_path, local: false, id: "achievement_form") do |f| %>
        <% current_user.daily_habits.each_with_index do |habit, i|  %>
          <div class='card-body'>
            <label class="text-center text-black"><input type="checkbox" name="achievement_daily[<%= i %>]" value="<%= habit.id %>"><%= habit.name %>→→<%= t('habits.index.total_d')%>:<%= habit.daily_achievements.count %> </label>
            <%= link_to "Delete", "/daily_habit/#{habit.id}", method: :delete, data: {confirm: "習慣が削除されます。本当によろしいですか？"} %>
          </div>
        <% end %>
        
        <div class='card'>
          <div class='card-header'>
            <h2 class="text-center text-black"><%= t('habits.index.title_w') %></h2>
          </div>  
          <% current_user.weekly_habits.each_with_index do |habit, j|  %>  
          <div class='card-body'>
            <label class="text-center text-black"><input type="checkbox" name="achievement_weekly[<%= j %>]" value="<%= habit.id %>"><%= habit.name %>→→<%=t('habits.index.total_w')%>:<%= habit.weekly_achievements.count %> </label>
            <%= link_to "Delete", "/weekly_habit/#{habit.id}", method: :delete, data: {confirm: "習慣が削除されます。本当によろしいですか？"} %>
          </div>
          <% end %>
          <%= button_tag type: :submit, id: "cat_image" do %>
            <%= render "cat_image" %>
          <% end %>
        </div>
      <% end %>
      
        <script>
        $('#cat_image').on('click', function(e) {
          e.preventDefault();
          $("#cat_image img").attr('src', '/images/cat_smile.png');
     
          setTimeout(function() {
            console.log('submit');
            $('#achievement_form').submit();
          }, 3000);
        });
        </script>
        
    </div>
  </div>
</div>

app/views/habits/new.html.erb
<div class="habits-new-wrapper">
  <div class="habits-container">
    <div class="row">
      <div class='col-md-8 mx-auto'>
        <div class='row'>
          <div class='col-md-6 mx-auto'>
            <h1 class="text-center text-black">Register your new habits!</h1>
            <%= form_for (@habit) do |f| %>
              <div class="form-group">
                <%= f.label "Daily Habit", class: 'text-black' %>
                <%= f.text_field :daily, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label "Weekly Habit", class: 'text-black' %>
                <%= f.text_field :weekly, class: 'form-control' %>
              </div>
              <%= f.submit "Send", class:"btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/habits/new_daily.html.erb
<div class="habits-new-wrapper">
  <div class="habits-container">
    <div class="row">
      <div class='col-md-8 mx-auto'>
        <div class='row'>
          <div class='col-md-6 mx-auto'>
            <h1 class="text-center text-black"><%= t('habits.new_daily.register') %></h1>
            <%= form_with(model: @habit, url: daily_habit_path) do |f| %>
              <div class="form-group">
                <%= f.label :name, "Type your new daily routine!" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <%= f.submit "Send", class:"btn btn-info" %>
              
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/habits/new_weekly.html.erb
<div class="habits-new-wrapper">
  <div class="habits-container">
    <div class="row">
      <div class='col-md-8 mx-auto'>
        <div class='row'>
          <div class='col-md-6 mx-auto'>
            <h1 class="text-center text-black"><%= t('habits.new_weekly.register') %></h1>
            <%= form_with(model: @habit, url: weekly_habit_path) do |f| %>
              <div class="form-group">
                <%= f.label :name, "Type your New weekly routine!" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <%= f.submit "Send", class:"btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/habits/save_achievement.js.erb
$("#cat_image").html("<%= j(render 'smile_cat_image')%>")