config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#index'
  get  '/about',   to: 'static_pages#about'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  post '/save_habit', to:'habits#save_achievement'
  resources :habits, only: [:index]
  resources :hobbies, only: [:index, :new, :create, :destroy]
  
  get '/hobbies/csv_output', to:'hobbies#csv_output'
  
  get '/daily_habit/new' => 'habits#new_daily'
  get '/weekly_habit/new' => 'habits#new_weekly'
  post '/daily_habit' => 'habits#create_daily'
  post '/weekly_habit' => 'habits#create_weekly'
  delete "/daily_habit/:id"=> "habits#daily_destroy"
  delete "/weekly_habit/:id"=> "habits#weekly_destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent navbar-dark bg-info">
  <a class="navbar-brand" href="/about" style="width:40px">
    <%= image_tag "icons/cat_home.png", class:'w-100' %>Habity
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
          <li class='nav-item' style='max-width:65px;' data-toggle="tooltip" title="Habit" data-placement="bottom">
            <%= link_to habits_path, class:'nav-link' do %>
              <%= image_tag "icons/footprint.png",class:'w-100'%>
            <% end %>
          </li>
          <li class='nav-item' style='max-width:65px;' data-toggle="tooltip" title="Hobby" data-placement="bottom">
            <%= link_to hobbies_path, class:'nav-link' do %>
              <%= image_tag "icons/footprint.png",class:'w-100' %>
            <% end %>
          </li>
          <li class='nav-item' style='max-width:65px;' data-toggle="tooltip" title="Users" data-placement="bottom">
            <%= link_to users_path , class:'nav-link' do %>
              <%= image_tag "icons/cat_user.png",class:'w-100' %>
            <% end %>
          </li>
          <li class="dropdown">
            <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">Language <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "English", "?locale=en" %></li>
              <li><%= link_to "Japanese", "?locale=ja" %></li>
            </ul>
          </li>
          <li class='nav-item' style='max-width:65px;'>
            <%= link_to logout_path, method: :delete, class:'nav-link' do %>
              <%= image_tag "icons/logout.png",class:'w-100' %>
            <% end %>
          </li>
        <% else %>
          <li class='nav-item' style='max-width:65px;'>
            <%= link_to new_user_path , class:'nav-link' do %>
              <%= image_tag "icons/register.png",class:'w-100' %>Signup
            <% end %>
          </li>
          <li class='nav-item' style='max-width:65px;'>
            <%= link_to login_path, class:'nav-link' do %>
              <%= image_tag "icons/login.png",class:'w-100' %>Login
            <% end %>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">Language <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "English", "?locale=en" %></li>
              <li><%= link_to "日本語", "?locale=ja" %></li>
            </ul>
          </li>
        <% end %>
    </ul>
    
    <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    });
    </script>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
      <% end %>
      
      <%= yield %>
      
      <script>
        $(function(){
          $(".alert").fadeOut(5000);
        });
      </script>
  </body>
</html>